### ISSUE TITLE
mod picked up as virus.

### ISSUE THREAD

**Issue by Dorrivix** [IcyVolcanoGitHub/New-Origins#2]
Ksyxis has been picked up as a virus by my antivirus. specifically it seems to be a trojan. the file with extension is Ksyxis-1,2,2,jar.bNIhAX

quick solution: temporarily remove mod.
proper solution: wait until mod update 1.2.3, which should be in a few days.
my temp solution: deleting the dependency string for ksyxis in the mrpack (opens with 7zip)

**Comment by Dorrivix** [comment]
a previous version of ksyxis (1.2.1) does not trigger the antivirus.

possible reason: mod and version flagged due to a panicked user with an infected computer.

**Comment by Radiated1cy** [comment]
Thanks for letting me know. It will be removed until it isn't labeled as a virus.
